sudo: required
services:
  - docker

before_install:
  - docker build -t mathrodrigues/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mathrodirgues/docker-react npm run test

language: generic 