sudo: required
services:
  - docker

before_install:
  - docker build -t mathrodrigues/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mathrodrigues/docker-react npm run test

language: generic 

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-104595594585"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"